'use client';
import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';

type Project = { id: string; name: string; description: string; _count: { assets: number }; updatedAt: string };
type SearchResult = { id: string; name: string; description: string; project: { id: string; name: string }; tags: { tag: { name: string } }[]; versions: { status: string; versionNo: number; sourceFileName?: string | null }[] };

export default function HomePage() {
  const [projects, setProjects] = useState<Project[]>([]); const [query, setQuery] = useState(''); const [results, setResults] = useState<SearchResult[]>([]); const [modal, setModal] = useState(false); const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [error, setError] = useState('');
  const load = async () => { const r = await fetch('/api/v1/projects', { credentials: 'include' }); if (r.status === 401) { window.location.href = '/login'; return; } setProjects(await r.json()); };
  useEffect(() => { load(); }, []);
  const create = async (e: FormEvent) => { e.preventDefault(); const r = await fetch('/api/v1/projects', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name, description }), credentials: 'include' }); if (!r.ok) { setError((await r.json()).error); return; } setModal(false); setName(''); setDescription(''); setError(''); load(); };
  const search = async (e: FormEvent) => { e.preventDefault(); if (!query.trim()) { setResults([]); return; } const r = await fetch(`/api/v1/search?q=${encodeURIComponent(query)}`, { credentials: 'include' }); setResults(await r.json()); };
  const logout = async () => { await fetch('/api/v1/auth/logout', { method: 'POST', credentials: 'include' }); window.location.href = '/login'; };
  return <div className="shell"><header className="topbar"><Link className="brand" href="/"><span className="brand-mark">P</span><span>Prototype Hub</span></Link><div className="top-actions"><span>个人工作区</span><button className="button ghost" onClick={logout}>退出</button></div></header><main className="page"><section className="hero"><div><div className="eyebrow">Prototype library</div><h1>原型资产，一处管理。</h1><p className="subtle">从本地 HTML 到可检索的产品研发资产，保留每一个可预览版本。</p></div><button className="button primary" onClick={() => setModal(true)}>＋ 新建项目</button></section><form className="toolbar" onSubmit={search}><input className="search" placeholder="搜索项目、原型、文件名、标签或页面文字…" value={query} onChange={e => setQuery(e.target.value)} /><button className="button secondary">搜索</button></form>{query && <section style={{ marginBottom: 40 }}><h2 style={{ marginBottom: 16 }}>搜索结果</h2>{results.length ? <div className="asset-list">{results.map(result => <Link className="asset-row" key={result.id} href={`/assets/${result.id}`}><div><h3>{result.name}</h3><div className="subtle">{result.project.name} · {result.versions[0] ? `v${result.versions[0].versionNo}${result.versions[0].sourceFileName ? ` · ${result.versions[0].sourceFileName}` : ''}` : '暂无版本'}</div></div><span className="arrow">查看 →</span></Link>)}</div> : <div className="empty">没有找到匹配的原型资产</div>}</section>}<section><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}><h2>我的项目</h2><span className="subtle">{projects.length} 个项目</span></div>{projects.length ? <div className="grid">{projects.map(project => <Link href={`/projects/${project.id}`} className="card project-card" key={project.id}><div className="card-top"><div><h3>{project.name}</h3><p className="subtle">{project.description || '还没有项目描述'}</p></div><span className="count">{project._count.assets} 个原型</span></div><div className="card-footer"><span>更新于 {new Date(project.updatedAt).toLocaleDateString('zh-CN')}</span><span className="arrow">进入项目 →</span></div></Link>)}</div> : <div className="empty">还没有项目，创建第一个项目开始管理原型。</div>}</section></main>{modal && <div className="modal-backdrop"><form className="modal" onSubmit={create}><h2>新建项目</h2><label className="field">项目名称<input autoFocus value={name} onChange={e => setName(e.target.value)} placeholder="例如：电商后台" /></label><label className="field">项目描述<textarea value={description} onChange={e => setDescription(e.target.value)} placeholder="这个项目用来管理什么原型？" /></label>{error && <p className="error">{error}</p>}<div className="modal-actions"><button type="button" className="button ghost" onClick={() => setModal(false)}>取消</button><button className="button primary">创建项目</button></div></form></div>}</div>;
}
