'use client';
import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';

type Asset = { id: string; name: string; description: string; _count: { versions: number }; tags: { tag: { name: string } }[]; updatedAt: string };
type Project = { id: string; name: string; description: string; assets: Asset[] };
export default function ProjectPage() {
  const { id } = useParams<{ id: string }>(); const [project, setProject] = useState<Project | null>(null); const [show, setShow] = useState(false); const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [tags, setTags] = useState(''); const [error, setError] = useState('');
  const load = async () => { const r = await fetch(`/api/v1/projects/${id}`, { credentials: 'include' }); if (r.status === 401) window.location.href = '/login'; else if (r.ok) setProject(await r.json()); }; useEffect(() => { load(); }, [id]);
  const create = async (e: FormEvent) => { e.preventDefault(); const r = await fetch(`/api/v1/projects/${id}/assets`, { method: 'POST', headers: { 'content-type': 'application/json' }, credentials: 'include', body: JSON.stringify({ name, description, tags: tags.split(',').map(v => v.trim()).filter(Boolean) }) }); if (!r.ok) { setError((await r.json()).error); return; } setShow(false); setName(''); setDescription(''); setTags(''); setError(''); load(); };
  if (!project) return <div className="page"><p className="subtle">正在加载…</p></div>;
  return <div className="shell"><header className="topbar"><Link className="brand" href="/"><span className="brand-mark">P</span><span>Prototype Hub</span></Link></header><main className="page"><div className="crumbs"><Link href="/">项目</Link>　/　{project.name}</div><section className="hero"><div><div className="eyebrow">Project</div><h1>{project.name}</h1><p className="subtle">{project.description || '管理这个项目下的所有原型版本。'}</p></div><button className="button primary" onClick={() => setShow(true)}>＋ 新建原型</button></section><div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 16 }}><h2>原型资产</h2><span className="subtle">{project.assets.length} 个资产</span></div>{project.assets.length ? <div className="asset-list">{project.assets.map(asset => <Link className="asset-row" href={`/assets/${asset.id}`} key={asset.id}><div><h3>{asset.name}</h3><p className="subtle">{asset.description || '暂无描述'} · {asset._count.versions} 个版本</p><div className="pills">{asset.tags.map(item => <span className="pill" key={item.tag.name}>{item.tag.name}</span>)}</div></div><span className="arrow">查看版本 →</span></Link>)}</div> : <div className="empty">项目里还没有原型资产。</div>}</main>{show && <div className="modal-backdrop"><form className="modal" onSubmit={create}><h2>新建原型资产</h2><label className="field">原型名称<input autoFocus value={name} onChange={e => setName(e.target.value)} placeholder="例如：订单详情页" /></label><label className="field">描述<textarea value={description} onChange={e => setDescription(e.target.value)} /></label><label className="field">标签<span><input value={tags} onChange={e => setTags(e.target.value)} placeholder="后台, 订单, v1（逗号分隔）" /></span></label>{error && <p className="error">{error}</p>}<div className="modal-actions"><button type="button" className="button ghost" onClick={() => setShow(false)}>取消</button><button className="button primary">创建资产</button></div></form></div>}</div>;
}
